name: lint

on:
  push:
    branches:
    - fallback
  pull_request:
    branches:
    - fallback

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4

    - uses: Roblox/setup-foreman@v3.1.0
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}
          allow-external-github-orgs: true

    - name: Lint
      run: |
        selene ./MainModule ./Loader
